# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-12 20:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_basket_lineitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lineitem',
            old_name='products',
            new_name='product',
        ),
    ]
