# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-17 18:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_lineitem_qty'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineItemOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_price', models.FloatField()),
                ('product_qty', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=30)),
                ('buyer_number', models.CharField(max_length=15)),
                ('delivery_country', models.CharField(max_length=100)),
                ('delivery_city', models.CharField(max_length=100)),
                ('delivery_address', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='lineitemorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Order'),
        ),
        migrations.AddField(
            model_name='lineitemorder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product'),
        ),
    ]
