# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-18 19:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20170718_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_ammount',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='promo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Promo'),
        ),
    ]
