# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-18 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20170718_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='promo',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
