# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-18 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20170718_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='promo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.Promo'),
        ),
        migrations.AlterField(
            model_name='order',
            name='promo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.Promo'),
        ),
    ]
