# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-19 08:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20170718_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 19, 8, 43, 52, 228262, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promo',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='promo',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
