# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-20 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20170720_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
